### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Advik-B** [nedsociety/pysandboxie#5]
```py
Traceback (most recent call last):
  File "e:\Github\PythonEval\test.py", line 8, in <module>
    sbie.create_sandbox('testpy', settings=settings)
  File "E:\Github\PythonEval\lib\pysandboxie\sandboxie\sandboxie.py", line 231, in create_sandbox
    cfg = self._readini()
  File "E:\Github\PythonEval\lib\pysandboxie\sandboxie\sandboxie.py", line 154, in _readini
    assert currentsection is not None
AssertionError
```

**Comment by nedsociety** [comment]
Can you upload the Sandboxie.ini file? Sounds like it's ill-formed somewhere at the beginning.

**Comment by leonardoamaro-dev** [comment]
I have same problem

**Comment by nedsociety** [comment]
From what @leonardoamaro-dev provided it seems the latest Sandboxie-plus adds some pre-section comments at the beginning of the file:
```
#
# Sandboxie-Plus configuration file
#
```

The latest commit (87ec0fa06ca20dfc060d33eee8412ca18fd52fe3) should have fixed this problem.

**Comment by Advik-B** [comment]
thanks
