### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by leonardoamaro-dev** [nedsociety/pysandboxie#7]
e.py
Traceback (most recent call last):
  File "c:\Users\OpenIT\Desktop\WhatsappPABX\core.py", line 8, in <module>
    sbie.create_sandbox('testpy', settings=settings)
  File "c:\Users\OpenIT\Desktop\WhatsappPABX\sandboxie\sandboxie.py", line 231, in create_sandbox
    cfg = self._readini()
  File "c:\Users\OpenIT\Desktop\WhatsappPABX\sandboxie\sandboxie.py", line 154, in _readini
    assert currentsection is not None
AssertionError

[Sandboxie.txt](https://github.com/nedsociety/pysandboxie/files/8704248/Sandboxie.txt)

I renamed file Sandboxie.txt to Sandboxie.ini

**Comment by nedsociety** [comment]
Duplicate of #5.
