### ISSUE TITLE
When it runs create_sandbox，it panic

### ISSUE THREAD

**Issue by ABetterCat** [nedsociety/pysandboxie#8]
my code：

`import sandboxie

sbie = sandboxie.Sandboxie()

settings = sbie.make_sandbox_setting('default')

sbie.create_sandbox('testpy', settings=settings)`

It returns panic as below.
`
Traceback (most recent call last):
  File "E:\install\PyCharm Community Edition 2021.3.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\install\PyCharm Community Edition 2021.3.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/project/sand/sand.py", line 9, in <module>
    sbie.create_sandbox('testpy', settings=settings)
  File "E:\project\sand\venv\lib\site-packages\sandboxie\sandboxie.py", line 243, in create_sandbox
    self._writeini(cfg)
  File "E:\project\sand\venv\lib\site-packages\sandboxie\sandboxie.py", line 159, in _writeini
    self._require_uac_admin()
  File "E:\project\sand\venv\lib\site-packages\sandboxie\sandboxie.py", line 128, in _require_uac_admin
    raise PermissionError('This operation requires UAC admin right')
PermissionError: This operation requires UAC admin right
python-BaseException
`

**Comment by nedsociety** [comment]
It say the error as is. You need to run the script on UAC to create/delete a sandbox or modify its settings.
